---
abstract: 'Parse/render human-readable configuration files with inheritance and schema validation'
author:
  - 'Igor Afanasyev <igor.afanasyev@gmail.com>'
build_requires:
  File::Slurp::Tiny: '0'
  Test::More: '0.94'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-Neat
provides:
  Config::Neat:
    file: lib/Config/Neat.pm
    version: '1.1'
  Config::Neat::Array:
    file: lib/Config/Neat/Array.pm
    version: '1.1'
  Config::Neat::Inheritable:
    file: lib/Config/Neat/Inheritable.pm
    version: '1.1'
  Config::Neat::Render:
    file: lib/Config/Neat/Render.pm
    version: '1.1'
  Config::Neat::Schema:
    file: lib/Config/Neat/Schema.pm
    version: '1.1'
  Config::Neat::Util:
    file: lib/Config/Neat/Util.pm
    version: '1.1'
requires:
  Tie::IxHash: '1.22'
resources:
  license: http://dev.perl.org/licenses/
version: '1.1'
